name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install
      run: |
        pip install pyside6 jdatetime
        pip install python-for-android

    - name: Build
      run: |
        p4a apk --name "Shahanshahi" --package org.myapp.calendar --version 1.0 --private . --presplash shahanshahi.png --orientation portrait
