name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies (Full)
      run: |
        pip install pyside6
        pip install jdatetime
        # نصب پکیج‌های کم‌کرده که در ارور آمده بود
        pip install jinja2 pkginfo tqdm packaging==24.1

    - name: Run PySide6 Deploy
      run: |
        pyside6-android-deploy init --input-file='shahanshahi andoid.py' --install-option accept-android-sdk-license --install-option accept-licenses
        pyside6-android-deploy build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: App-Artifact
        path: |
          build/build/outputs/apk/debug/*.apk
          build/**/*.apk
