name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install pyside6
        pip install jinja2 pkginfo tqdm packaging==24.1
        pip install jdatetime

    - name: Build APK
      run: |
        # پیدا کردن فایل‌های wheel با دستور find لینوکس (راه حلی برای مشکل قبلی)
        WHEEL_PYSIDE=$(find /opt/hostedtoolcache/Python/ -name "PySide6-*.whl" | head -n 1)
        WHEEL_SHIBOKEN=$(find /opt/hostedtoolcache/Python/ -name "shiboken6-*.whl" | head -n 1)

        # اگر find چیزی پیدا نکرد، به مسیرهای جایگزین نگاه میکنیم
        if [ -z "$WHEEL_PYSIDE" ]; then
            WHEEL_PYSIDE=$(python -c "import PySide6; import sys; print(sys.path[0] + '/site-packages/PySide6.dist-info/RECORD')" 2>/dev/null | head -c 1)
        fi

        echo "Found Pyside: $WHEEL_PYSIDE"
        echo "Found Shiboken: $WHEEL_SH
